### ISSUE TITLE
Link needs to be a hotlink

### ISSUE THREAD

**Issue by kiowadriver** [hendrixjoseph/tagger#6]
I like the app. It is simple and addresses the use case. 

I have shared the app with family and friends who would also like to support my affiliate link when shopping on their own phones.  When you get to the Tagger page.  If the hyperlink were a hotlink, it could send the user back to their amazon app so they could complete the purchase with the affiliate tag added.  Right now, they would have to share it to a SMS and then click on the link.

**Comment by hendrixjoseph** [comment]
Ok, I've thought about this for a few days and I think I understand what you mean.

Right now, the app works the following way when you share an Amazon link to the app:
* Find item on Amazon.
* Click share button.
* Share to Tagger.
* Click TagIt! button.
* Share dialog comes up. Amazon or web browser are not an option.

What you are suggesting is something like the following:
* Find item on Amazon.
* Click share button.
* Share to Tagger.
* Click TagIt! button.
* Return to the Amazon app or web browser.

I think what you're suggesting might be against the TOS for Amazon Associates; nevertheless I can see a legit use case for that functionality.

The relevant code I'll have to add might look something like the following:

```java
String url = "http://www.example.com";
Intent i = new Intent(Intent.ACTION_VIEW);
i.setData(Uri.parse(url));
startActivity(i); 
```

**Comment by kiowadriver** [comment]
Yes, I think you have it.  Essentially this allows a user to use the amazon mobile app to browse for a product but before purchasing they can use this process to generate the affiliate link for that product and complete the purchase through either the web or mobile amazon application.

**Comment by hendrixjoseph** [comment]
@kiowadriver I've made this update (and several others) and pushed the changes to the Google Play store. It should be available now.

Let me know if it works as excepted. Thanks!
